// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductLine.Data;

namespace ProductLine.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210706152352_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductLine.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "ACategory"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "BCategory"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "CCategory"
                        });
                });

            modelBuilder.Entity("ProductLine.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(5691),
                            ProductId = 1,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(6960),
                            ProductId = 1,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(6993),
                            ProductId = 1,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7012),
                            ProductId = 1,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7029),
                            ProductId = 1,
                            Url = "demo5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7049),
                            ProductId = 2,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7066),
                            ProductId = 2,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7083),
                            ProductId = 2,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7099),
                            ProductId = 2,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7117),
                            ProductId = 2,
                            Url = "demo5.jpg"
                        },
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7133),
                            ProductId = 3,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7149),
                            ProductId = 3,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7198),
                            ProductId = 3,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7215),
                            ProductId = 3,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7231),
                            ProductId = 3,
                            Url = "demo5.jpg"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7246),
                            ProductId = 4,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7262),
                            ProductId = 4,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7279),
                            ProductId = 4,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7295),
                            ProductId = 4,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7312),
                            ProductId = 4,
                            Url = "demo5.jpg"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7328),
                            ProductId = 5,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7343),
                            ProductId = 5,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7359),
                            ProductId = 5,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7375),
                            ProductId = 5,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7391),
                            ProductId = 5,
                            Url = "demo5.jpg"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7408),
                            ProductId = 6,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7423),
                            ProductId = 6,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7439),
                            ProductId = 6,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7454),
                            ProductId = 6,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7470),
                            ProductId = 6,
                            Url = "demo5.jpg"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7485),
                            ProductId = 7,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7501),
                            ProductId = 7,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7541),
                            ProductId = 7,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7561),
                            ProductId = 7,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7577),
                            ProductId = 7,
                            Url = "demo5.jpg"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7593),
                            ProductId = 8,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7609),
                            ProductId = 8,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7625),
                            ProductId = 8,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7641),
                            ProductId = 8,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7658),
                            ProductId = 8,
                            Url = "demo5.jpg"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7673),
                            ProductId = 9,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7688),
                            ProductId = 9,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7704),
                            ProductId = 9,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7720),
                            ProductId = 9,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7736),
                            ProductId = 9,
                            Url = "demo5.jpg"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7751),
                            ProductId = 10,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7766),
                            ProductId = 10,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7782),
                            ProductId = 10,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7798),
                            ProductId = 10,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7814),
                            ProductId = 10,
                            Url = "demo5.jpg"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7831),
                            ProductId = 11,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7846),
                            ProductId = 11,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7903),
                            ProductId = 11,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7922),
                            ProductId = 11,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7938),
                            ProductId = 11,
                            Url = "demo5.jpg"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7954),
                            ProductId = 12,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7970),
                            ProductId = 12,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(7986),
                            ProductId = 12,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8002),
                            ProductId = 12,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8018),
                            ProductId = 12,
                            Url = "demo5.jpg"
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8034),
                            ProductId = 13,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8050),
                            ProductId = 13,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8066),
                            ProductId = 13,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8083),
                            ProductId = 13,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8099),
                            ProductId = 13,
                            Url = "demo5.jpg"
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8117),
                            ProductId = 14,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8133),
                            ProductId = 14,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8150),
                            ProductId = 14,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8166),
                            ProductId = 14,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8182),
                            ProductId = 14,
                            Url = "demo5.jpg"
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8198),
                            ProductId = 15,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8241),
                            ProductId = 15,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8257),
                            ProductId = 15,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8273),
                            ProductId = 15,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8289),
                            ProductId = 15,
                            Url = "demo5.jpg"
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8305),
                            ProductId = 16,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8321),
                            ProductId = 16,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8337),
                            ProductId = 16,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8352),
                            ProductId = 16,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8368),
                            ProductId = 16,
                            Url = "demo5.jpg"
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8384),
                            ProductId = 17,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8401),
                            ProductId = 17,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8417),
                            ProductId = 17,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8448),
                            ProductId = 17,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 80,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8464),
                            ProductId = 17,
                            Url = "demo5.jpg"
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8479),
                            ProductId = 18,
                            Url = "demo1.jpg"
                        },
                        new
                        {
                            Id = 82,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8495),
                            ProductId = 18,
                            Url = "demo2.jfif"
                        },
                        new
                        {
                            Id = 83,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8511),
                            ProductId = 18,
                            Url = "demo3.jfif"
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8527),
                            ProductId = 18,
                            Url = "demo4.jpg"
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(8542),
                            ProductId = 18,
                            Url = "demo5.jpg"
                        });
                });

            modelBuilder.Entity("ProductLine.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssemblyNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CretaedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssemblyNr = "A12",
                            CategoryId = 1,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 227, DateTimeKind.Local).AddTicks(2287),
                            Description = "Description of brake-1",
                            Name = "Brake-1",
                            RefNumber = "ABC123"
                        },
                        new
                        {
                            Id = 2,
                            AssemblyNr = "A13",
                            CategoryId = 1,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(3945),
                            Description = "Description of brake-2",
                            Name = "Brake-2",
                            RefNumber = "ABC124"
                        },
                        new
                        {
                            Id = 3,
                            AssemblyNr = "A14",
                            CategoryId = 1,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(4000),
                            Description = "Description of brake-3",
                            Name = "Brake-3",
                            RefNumber = "ABC125"
                        },
                        new
                        {
                            Id = 4,
                            AssemblyNr = "A15",
                            CategoryId = 2,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(4023),
                            Description = "Description of Steer-1",
                            Name = "Steer-1",
                            RefNumber = "ABC126"
                        },
                        new
                        {
                            Id = 5,
                            AssemblyNr = "A16",
                            CategoryId = 2,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(4041),
                            Description = "Description of Steer--2",
                            Name = "Steer-2",
                            RefNumber = "ABC127"
                        },
                        new
                        {
                            Id = 6,
                            AssemblyNr = "A17",
                            CategoryId = 2,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(4064),
                            Description = "Description of Steer-3",
                            Name = "Steer-3",
                            RefNumber = "ABC128"
                        },
                        new
                        {
                            Id = 7,
                            AssemblyNr = "A18",
                            CategoryId = 3,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(4082),
                            Description = "Description of Filter-1",
                            Name = "Filter-1",
                            RefNumber = "ABC226"
                        },
                        new
                        {
                            Id = 8,
                            AssemblyNr = "A19",
                            CategoryId = 3,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(4099),
                            Description = "Description of Filter--2",
                            Name = "Filter-2",
                            RefNumber = "ABC227"
                        },
                        new
                        {
                            Id = 9,
                            AssemblyNr = "A10",
                            CategoryId = 3,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(4115),
                            Description = "Description of Filter-3",
                            Name = "Filter-3",
                            RefNumber = "ABC228"
                        },
                        new
                        {
                            Id = 10,
                            AssemblyNr = "A12",
                            CategoryId = 1,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(4134),
                            Description = "Description of brake-11",
                            Name = "Brake-11",
                            RefNumber = "ABd123"
                        },
                        new
                        {
                            Id = 11,
                            AssemblyNr = "A13",
                            CategoryId = 1,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(4151),
                            Description = "Description of brake-21",
                            Name = "Brake-21",
                            RefNumber = "ABD124"
                        },
                        new
                        {
                            Id = 12,
                            AssemblyNr = "A14",
                            CategoryId = 1,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(4277),
                            Description = "Description of brake-31",
                            Name = "Brake-31",
                            RefNumber = "ABZ125"
                        },
                        new
                        {
                            Id = 13,
                            AssemblyNr = "A15",
                            CategoryId = 2,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(4297),
                            Description = "Description of Steer-11",
                            Name = "Steer-11",
                            RefNumber = "ABS126"
                        },
                        new
                        {
                            Id = 14,
                            AssemblyNr = "A16",
                            CategoryId = 2,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(4314),
                            Description = "Description of Steer--21",
                            Name = "Steer-21",
                            RefNumber = "ABE127"
                        },
                        new
                        {
                            Id = 15,
                            AssemblyNr = "A17",
                            CategoryId = 2,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(4331),
                            Description = "Description of Steer-31",
                            Name = "Steer-31",
                            RefNumber = "ABA128"
                        },
                        new
                        {
                            Id = 16,
                            AssemblyNr = "A18",
                            CategoryId = 3,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(4348),
                            Description = "Description of Filter-11",
                            Name = "Filter-11",
                            RefNumber = "ABK226"
                        },
                        new
                        {
                            Id = 17,
                            AssemblyNr = "A19",
                            CategoryId = 3,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(4366),
                            Description = "Description of Filter--21",
                            Name = "Filter-21",
                            RefNumber = "ABM227"
                        },
                        new
                        {
                            Id = 18,
                            AssemblyNr = "A10",
                            CategoryId = 3,
                            CretaedAt = new DateTime(2021, 7, 6, 17, 23, 52, 229, DateTimeKind.Local).AddTicks(4384),
                            Description = "Description of Filter-31",
                            Name = "Filter-31",
                            RefNumber = "ABH228"
                        });
                });

            modelBuilder.Entity("ProductLine.Entities.Photo", b =>
                {
                    b.HasOne("ProductLine.Entities.Product", "Product")
                        .WithMany("Photos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductLine.Entities.Product", b =>
                {
                    b.HasOne("ProductLine.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductLine.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProductLine.Entities.Product", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
